### PR TITLE
Fix crash on anonymous type parameter to implicit class

### LINKED ISSUE #366: Crash on anonymous type parameters of implicit classes
```scala
object M {
  implicit class C[_](x: Int) {
    def m: Int = ???
  }
}
```

```
error: compiler crash: None.get
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at rsc.outline.Synthesizer$$anonfun$14.rsc$outline$Synthesizer$$anonfun$$synthesize$1(Synthesizer.scala:157)
	at rsc.outline.Synthesizer$$anonfun$14$$anonfun$15.apply(Synthesizer.scala:158)
	at rsc.outline.Synthesizer$$anonfun$14$$anonfun$15.apply(Synthesizer.scala:158)
	at scala.collection.immutable.List.map(List.scala:284)
	at rsc.outline.Synthesizer$$anonfun$14.rsc$outline$Synthesizer$$anonfun$$synthesize$1(Synthesizer.scala:158)
	at rsc.outline.Synthesizer$$anonfun$14.apply(Synthesizer.scala:164)
	at rsc.outline.Synthesizer$$anonfun$14.apply(Synthesizer.scala:154)
	at scala.collection.immutable.List.map(List.scala:284)
	at rsc.outline.Synthesizer.implicitClassConversion(Synthesizer.scala:154)
	at rsc.outline.Scheduler$$anonfun$stats$2.apply(Scheduler.scala:515)
	at rsc.outline.Scheduler$$anonfun$stats$2.apply(Scheduler.scala:503)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at rsc.outline.Scheduler.stats(Scheduler.scala:503)
	at rsc.outline.Scheduler.defnTemplate(Scheduler.scala:341)
	at rsc.outline.Scheduler.apply(Scheduler.scala:35)
	at rsc.outline.Scheduler$$anonfun$stats$2.apply(Scheduler.scala:512)
	at rsc.outline.Scheduler$$anonfun$stats$2.apply(Scheduler.scala:503)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at rsc.outline.Scheduler.stats(Scheduler.scala:503)
	at rsc.outline.Scheduler.source(Scheduler.scala:470)
	at rsc.outline.Scheduler.apply(Scheduler.scala:38)
	at rsc.Compiler$$anonfun$rsc$Compiler$$schedule$1.apply(Compiler.scala:108)
	at rsc.Compiler$$anonfun$rsc$Compiler$$schedule$1.apply(Compiler.scala:106)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at rsc.Compiler.rsc$Compiler$$schedule(Compiler.scala:106)
	at rsc.Compiler$$anonfun$phases$3.apply$mcV$sp(Compiler.scala:70)
	at rsc.Compiler$$anonfun$run$2.apply(Compiler.scala:36)
	at rsc.Compiler$$anonfun$run$2.apply(Compiler.scala:33)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at rsc.Compiler.run(Compiler.scala:33)
	at rsc.cli.Main$.process(Main.scala:35)
	at rsc.cli.Main$.main(Main.scala:14)
	at rsc.cli.Main.main(Main.scala)
```

### PR DESCRIPTION
**Pull request by sundresh**
Fix crash on anonymous type parameter to implicit class. There are a couple of TODO comments to resolve before merging this, but feel free to review (including suggestions for the TODO comments).

Closes #366

### CODE REVIEW

File: rsc/src/main/scala/rsc/outline/Synthesizer.scala [hunk 1]
```diff
@@ -175,8 +184,21 @@ final class Synthesizer private (
...
+      // Convert the implicit class's type parameters to the factory method return type parameters.
+      // This is necessary because the type parameters of a class or method definition can include
+      // constraints like upper and lower bounds, while a method return type can only include
+      // concrete type names and type variables that were bound in the method's type parameters.
+      val retTparams = tparams.map(_.id match {
+        case tptId: TptId => tptId
+        // AnonId represents `_`, which doesn't make sense as a type parameter in the return type;
+        // replace it by `Any`, i.e., `_root_.scala.Any`
+        case anonId: AnonId =>
+          // TODO: Define this constant somewhere
```
Comment (WiWa) [inline rsc/src/main/scala/rsc/outline/Synthesizer.scala]: so something like `rsc.semantics.Stdlib` but next to `rsc.syntax.Trees`?

Comment (sundresh) [reply rsc/src/main/scala/rsc/outline/Synthesizer.scala]: Yeah. Or do you know if there's an appropriate method to convert a `String` to a `Tpt` (maybe something intentionally exposed by the parser)? I'll take a look at the rest of `Synthesizer.scala` to see if there's an existing pattern for this sort of thing.

Comment (sundresh) [reply rsc/src/main/scala/rsc/outline/Synthesizer.scala]: It looks like the standard pattern used here is `TptId("Any").withSym(AnyClass)`

File: rsc/src/main/scala/rsc/outline/Synthesizer.scala [hunk 2]
```diff
@@ -175,8 +184,19 @@ final class Synthesizer private (
...
       val core = tree.id
-      if (tparams.isEmpty) Some(core)
-      else Some(TptParameterize(core, tparams.map(_.id.asInstanceOf[TptId])))
+      // Convert the implicit class's type parameters to the factory method return type parameters.
+      // This is necessary because the type parameters of a class or method definition can include
+      // constraints like upper and lower bounds, while a method return type can only include
+      // concrete type names and type variables that were bound in the method's type parameters.
+      val retTparams = tparams.map(_.id match {
+        case tptId: TptId => tptId
+        // AnonId represents `_`, which doesn't make sense as a type parameter in the return type;
```
Comment (WiWa) [inline rsc/src/main/scala/rsc/outline/Synthesizer.scala]: Not sure why it doesn't make sense?

File: rsc/src/main/scala/rsc/outline/Synthesizer.scala [hunk 3]
```diff
@@ -175,8 +184,19 @@ final class Synthesizer private (
...
+        // replace it by `Any`, i.e., `_root_.scala.Any`
+        case anonId: AnonId => TptId("Any").withSym(AnyClass)
+        case nonTptNamedId: NamedId => crash(nonTptNamedId.pos, nonTptNamedId)
```
Comment (WiWa) [inline rsc/src/main/scala/rsc/outline/Synthesizer.scala]: I don't think this is exhaustive; we can maybe say `case otherId =>`

File: rsc/src/main/scala/rsc/outline/Synthesizer.scala (hunk 2 above)
Comment (sundresh) [reply rsc/src/main/scala/rsc/outline/Synthesizer.scala]: All type variables in return types must be bound, but `_` can only be used to represent an anonymous unbound type variable. Would it be clearer to say "isn't valid" rather than "doesn't make sense"?

File: rsc/src/main/scala/rsc/outline/Synthesizer.scala (hunk 3 above)
Comment (sundresh) [reply rsc/src/main/scala/rsc/outline/Synthesizer.scala]: CI was failing because this was a non-exhaustive match without the `NamedId` fallback, but it is passing now. Here's why:
1. `TypeParam#id` has type `UnambigId`
1. `UnambigId` is a sealed trait with two implementations, `AnonId` and `NamedId`
1. `NamedId` is a sealed trait with four implementations: `CtorId`, `PatId`, `TermId`, `TptId`

File: rsc/src/main/scala/rsc/outline/Synthesizer.scala (hunk 2 above)
Comment (WiWa) [reply rsc/src/main/scala/rsc/outline/Synthesizer.scala]: I was looking at it from the viewpoint that you could technically have a `def foo: C[_] = new C`
