### PR TITLE
fix ascription when extending from non-polymorphic trait with polymor…

### LINKED ISSUE #456: Incorrect type parameter ascription when extending from nonpolymorphic trait with polymorphic grandparent class
```scala
  class C[A]

  trait T extends C[Int]

  class D extends T
```

```diff
--- obtained
+++ expected
@@ -7,3 +7,3 @@
∙
-  class D extends T[Int]
+  class D extends T
 }
```

Basically, RscCompat will incorrectly ascribe type parameters to the extends trait. This also happens when `C` is `abstract class` but not when it's a `trait`.

### PR DESCRIPTION
**Pull request by ShaneDelmore**
…phic grandparent class (fix #456)

### CODE REVIEW

File: scalafix/rules/src/main/scala/rsc/rules/RscCompat.scala [hunk 1]
```diff
@@ -129,8 +130,12 @@ case class RscCompat(legacyIndex: SemanticdbIndex, config: RscCompatConfig)
           val name = templ.name.get
           inits.headOption.foreach { init =>
             val tokens = init.tpe.tokens
-            // If type params of init may be inferred
-            if (!tokens.exists(_.is[Token.LeftBracket])) {
+            lazy val isTrait = (for {
+              symbol <- init.symbol
```
Comment (wiwa) [inline scalafix/rules/src/main/scala/rsc/rules/RscCompat.scala]: we might want to just crash if there isn't a symbol for this?

File: scalafix/output/src/main/scala/rsc/tests/BetterRscCompat.scala [hunk 2]
```diff
@@ -263,4 +263,12 @@ object BetterRscCompat_Test {
   object NestedTuples {
     val foo: ((String, Int), Double) = (("1", 1), 1.0)
   }
+
+  object PolymorphicGrandparent {
+    class C[A]
```
Comment (wiwa) [inline scalafix/output/src/main/scala/rsc/tests/BetterRscCompat.scala]: We probably want to have test cases for `abstract class` instead of `class` or `trait`.
